### ISSUE TITLE
Item durability or enchantment is reset in refined 2 milestone 2

### ISSUE THREAD

**Issue by big-julius** [refinedmods/refinedstorage2#203] opened 2022-07-30 21:45 UTC
### Describe the bug

Hello,

When storing enchantable items and items with duraility in the grid : enchantments and durability are reset when getting back the items from the grid.
This bug was reproduced with shears, tools, armor pieces, enchanted books

### How can we reproduce this bug or crash?

1. Have a refined grid + disks
2. Enchant a pickaxe and use it to lower its durability (works with enchanted only or damaged only item)
3. Put the pickaxe in the grid
4. Get the pickaxe from the grid : the pickaxe durability is reset and enchantments are removed

### What Minecraft version is this happening on?

Minecraft 1.19

### What Forge or Fabric version is this happening on?

Forge 42.0.1

### What Refined Storage version is this happening on?

RS 2.0.0-milestone.2.1

**Comment by raoulvdberge** [comment] 2022-07-31 08:19
I can't reproduce this:

![java_upBYggRJJd](https://user-images.githubusercontent.com/10358424/182017117-3a2c3c98-e903-48f5-b1d9-47ffa8f87908.gif)

**Comment by raoulvdberge** [comment] 2022-07-31 08:20
Are you sure that you are on `v2.0.0-milestone.2.1`? This bug *did* exist, but was fixed in 2.1.

**Comment by big-julius** [comment] 2022-07-31 10:06
I downloaded and compiled it yesterday.
![2022-07-31_11-58](https://user-images.githubusercontent.com/97511226/182021220-abd70a76-76ea-4789-9e90-32434289898c.png)
![rs-nbt-reset](https://user-images.githubusercontent.com/97511226/182021377-c9a8b1ed-8f60-403d-a783-8b69b40fe6c8.gif)


I will try to clear all caches and recompile it to be sure and tell you after.

**Comment by raoulvdberge** [comment] 2022-07-31 10:15
If you downloaded and compiled yourself, you need to mention that! The in-development version doesn't have any marker. You could have a  `v2.0.0-milestone.2.1` without the bugfix.

 `v2.0.0-milestone.2.1` has been officially released yesterday, with a bugfix for NBT items. That fix has been done in the late afternoon, so grab the latest published release.

**Closed as not planned** 2022-07-31 10:19 UTC
Labels: bug, invalid

**Comment by big-julius** [comment] 2022-07-31 10:42
Ok. Where do you publish the pre-compiled version please?

**Comment by raoulvdberge** [comment] 2022-07-31 10:43
https://github.com/refinedmods/refinedstorage2/releases/tag/v2.0.0-milestone.2.1
