### ISSUE TITLE
Certain items are unable to be extracted via GUI

### ISSUE THREAD

**Issue by luigistyle** [refinedmods/refinedstorage2#528] opened 2024-05-20 19:51 UTC
### Describe the bug

As per the title, it seems items with specific NBT are not able to be extracted from the Grid GUI, and are only able to be pulled via an extractor with a filter. Restarting the server or moving the items/disks to a new storage network is ineffective.
Provided below is NBT data from a bugged item that I was not able to extract from the storage system on my server. Note that this NBT is provided by the mod [Zenith](https://modrinth.com/mod/zenith), a Fabric port of [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis).

`{id: "minecraft:iron_leggings", tag: {Damage: 0, affix_data: {name: '{"color":"#5555FF","translate":"misc.zenith.affix_name.three","with":[{"translate":"affix.zenith:armor/dmg_reduction/dwarven"},"",{"translate":"affix.zenith:armor/attribute/spiritual.suffix"}]}', sockets: 2, affixes: {"zenith:armor/dmg_reduction/dwarven": 0.5079668f, "zenith:durable": 0.16f, "zenith:armor/attribute/spiritual": 0.17064679f, "zenith:armor/attribute/windswept": 0.47741085f, "zenith:armor/attribute/ironforged": 0.47762716f}, rarity: "zenith:rare"}, apoth_rchest: 1b}, Count: 1b}`

I am experiencing this issue on Minecraft 1.20.1, despite being forced to mark it as a 1.20.4 issue in the selector.

### How can we reproduce this bug or crash?

1. Create a conventional storage system with a grid, controller and disk drive
2. Insert an item with NBT data that the storage system doesn't like (bad NBT example provided in issue description)
3. Attempt to manually extract the item from the system by interacting with the Grid and shift clicking or clicking the item

### What Minecraft version is this happening on?

Minecraft 1.20.4

### What NeoForge or Fabric version is this happening on?

Loader 0.15.11 / API 0.92.1

### What Refined Storage version is this happening on?

refinedstorage2-platform-fabric-2.0.0-milestone.3.2

### Relevant log output

```shell
N/A (No Relevant Log Output)
```

**Comment by raoulvdberge** [comment] 2024-06-09 11:16
I tried to `/give` me those iron leggings with the nbt data, but couldn't reproduce the bug. I was able to extract.

Then I tried to reproduce with "Zenith" but unfortunately the mod isn't available on 1.20.4.

I'll close this issue as there is not much I can do further. Feel free to provide more reproduction steps/information for 1.20.4.

**Closed as completed by raoulvdberge** 2024-06-09 11:16 UTC
Labels: bug, can't reproduce
