### ISSUE TITLE
Broke Receiver with External Storage Connected, Picked up block, Server Crashed.

### ISSUE THREAD

**Issue by Agent40infinity** [refinedmods/refinedstorage2#739] opened 2024-12-08 02:02 UTC
### Describe the bug

https://pastebin.com/drFQKDMG

### How can we reproduce this bug or crash?

1. Receiver with external storage connected via network card to main controller randomly went dark. 
2. Confused, broke the receiver. Block dropped on the ground.
3. Picked up the block.
4. Server crashed.

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

NeoForge-21.1.83

### What Refined Storage version is this happening on?

v2.0.0-milestone.4.10

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-12-08 01:24:33
Description: Ticking block entity

java.lang.IllegalStateException: Network of resulting removed node (com.refinedmods.refinedstorage.api.network.impl.node.SimpleNetworkNode@78605356) cannot be empty
at TRANSFORMER/refinedstorage@2.0.0-milestone.4.10/com.refinedmods.refinedstorage.api.network.impl.NetworkBuilderImpl.lambda$splitNetworks$2(NetworkBuilderImpl.java:167) ~[refinedstorage-neoforge-2.0.0-milestone.4.10.jar%23748!/:?] {re:classloading}
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?] {}
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?] {}
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
```

Refer to pastebin for full log.

**Comment by raoulvdberge** [comment] 2024-12-08 10:33
I cannot reproduce it with these reproduction steps. Can you reproduce it reliably?

**Comment by Agent40infinity** [comment] 2024-12-08 11:03
Unable to reproduce reliably, randomly occurs. Happened 3 times, randomly occurs during server uptime

**Comment by raoulvdberge** [comment] 2024-12-12 16:52
I'll have to close this unfortunately, if it's not reproduceable reliably I can't do much.

**Closed as completed by raoulvdberge** 2024-12-12 16:52 UTC
Labels: bug, can't reproduce
